export type TransportCommune = {
  communeCode: string
  commune: string
}

export const TRANSPORT_COMMUNES: TransportCommune[] = [
  { communeCode: "ALHUE", commune: "Alhué" },
  { communeCode: "BUIN", commune: "Buin" },
  { communeCode: "CALERA_DE_TANGO", commune: "Calera de Tango" },
  { communeCode: "CERRILLOS", commune: "Cerrillos" },
  { communeCode: "CERRO_NAVIA", commune: "Cerro Navia" },
  { communeCode: "CHICUREO", commune: "Chicureo" },
  { communeCode: "COLINA", commune: "Colina" },
  { communeCode: "CONCHALI", commune: "Conchalí" },
  { communeCode: "CURACAVI", commune: "Curacaví" },
  { communeCode: "EL_BOSQUE", commune: "El Bosque" },
  { communeCode: "EL_MONTE", commune: "El Monte" },
  { communeCode: "ESTACION_CENTRAL", commune: "Estación Central" },
  { communeCode: "HUECHURABA", commune: "Huechuraba" },
  { communeCode: "INDEPENDENCIA", commune: "Independencia" },
  { communeCode: "ISLA_DE_MAIPO", commune: "Isla de Maipo" },
  { communeCode: "LAMPA", commune: "Lampa" },
  { communeCode: "LAS_CONDES", commune: "Las Condes" },
  { communeCode: "LA_CISTERNA", commune: "La Cisterna" },
  { communeCode: "LA_FLORIDA", commune: "La Florida" },
  { communeCode: "LA_GRANJA", commune: "La Granja" },
  { communeCode: "LA_PINTANA", commune: "La Pintana" },
  { communeCode: "LA_REINA", commune: "La Reina" },
  { communeCode: "LO_BARNECHEA", commune: "Lo Barnechea" },
  { communeCode: "LO_ESPEJO", commune: "Lo Espejo" },
  { communeCode: "LO_PRADO", commune: "Lo Prado" },
  { communeCode: "MACUL", commune: "Macul" },
  { communeCode: "MAIPU", commune: "Maipú" },
  { communeCode: "MARIA_PINTO", commune: "María Pinto" },
  { communeCode: "MELIPILLA", commune: "Melipilla" },
  { communeCode: "NUNOA", commune: "Ñuñoa" },
  { communeCode: "PADRE_HURTADO", commune: "Padre Hurtado" },
  { communeCode: "PAINE", commune: "Paine" },
  { communeCode: "PEDRO_AGUIRRE_CERDA", commune: "Pedro Aguirre Cerda" },
  { communeCode: "PENAFLOR", commune: "Peñaflor" },
  { communeCode: "PENALOLEN", commune: "Peñalolén" },
  { communeCode: "PIRQUE", commune: "Pirque" },
  { communeCode: "PROVIDENCIA", commune: "Providencia" },
  { communeCode: "PUDAHUEL", commune: "Pudahuel" },
  { communeCode: "PUENTE_ALTO", commune: "Puente Alto" },
  { communeCode: "QUILICURA", commune: "Quilicura" },
  { communeCode: "QUINTA_NORMAL", commune: "Quinta Normal" },
  { communeCode: "RECOLETA", commune: "Recoleta" },
  { communeCode: "RENCA", commune: "Renca" },
  { communeCode: "SANTIAGO", commune: "Santiago" },
  { communeCode: "SAN_BERNARDO", commune: "San Bernardo" },
  { communeCode: "SAN_JOAQUIN", commune: "San Joaquín" },
  { communeCode: "SAN_JOSE_DE_MAIPO", commune: "San José de Maipo" },
  { communeCode: "SAN_MIGUEL", commune: "San Miguel" },
  { communeCode: "SAN_PEDRO", commune: "San Pedro" },
  { communeCode: "SAN_RAMON", commune: "San Ramón" },
  { communeCode: "TALAGANTE", commune: "Talagante" },
  { communeCode: "TILTIL", commune: "Tiltil" },
  { communeCode: "VITACURA", commune: "Vitacura" },
]

export function getTransportCommuneByCode(communeCode: string) {
  return TRANSPORT_COMMUNES.find((item) => item.communeCode === communeCode)
}
